<a href="https://colab.research.google.com/github/SaavedraLuana/music-listening-analytics/blob/main/music_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
print("Hello,Music")

Hello,Music

In [29]:
import pandas as pd

In [30]:
music = pd.read_csv("https://raw.githubusercontent.com/SaavedraLuana/music-listening-analytics/main/data/listening_history.csv")

In [31]:
music

         date  time          artist                        song
0  2026-09-09   NaN         Solange                      Almeda
1  2026-09-09   NaN         Solange                      Jerrod
2  2026-09-09   NaN          Kelela                      Linknb
3  2026-09-09   NaN          Kelela                      Sorbet
4  2026-09-09   NaN  PinkPantheress                      Reason
5  2026-09-09   NaN   Azealia Banks  Heavy Metal and Reflective
6  2026-09-09   NaN          SOPHIE    Is It Cold in the Water?
7  2026-09-09   NaN    Pearly Drops             Oppressive Face
8  2026-09-09   NaN       FKA twigs                Lightbeamers
9  2026-09-09   NaN        Operelly                Encyclopedia

In [32]:
music["song"].count()

np.int64(10)

In [33]:
music["artist"].nunique()

8

In [34]:
music["artist"].value_counts().head(3)

artist
Solange           2
Kelela            2
PinkPantheress    1
Name: count, dtype: int64